// ============================================================================
// Nexify — Delivery Engine
// AI project plan generation + GitHub repo creation.
// Called synchronously after proposal acceptance.
// ============================================================================

import { getDb } from '@/lib/db'
import { getLead } from '@/lib/db/queries'
import { complete } from '@/lib/ai/providers/client'
import { createRepo, createFile, isGitHubConfigured } from '@/lib/github'

export async function startDelivery(projectId: string): Promise<{ success: boolean; error?: string }> {
  try {
    const db = getDb()
    const project = db.prepare('SELECT * FROM projects WHERE id = ?').get(projectId) as any
    if (!project) return { success: false, error: 'Project not found' }

    const lead = project.lead_id ? getLead(project.lead_id) : null
    if (!lead) return { success: false, error: 'Lead not found for project' }

    // 1. AI generates project plan
    const aiResponse = await complete({
      messages: [
        {
          role: 'system',
          content: `You are Dev-Alpha, senior full-stack engineer at Nexify. Generate a detailed project plan with milestones.
          Return JSON only (no markdown, no code blocks):
          {"milestones":[{"title":"Sprint 1: ...","description":"...","weeks":2,"tasks":["..."]}],"techStack":["React","Node.js"],"estimatedWeeks":8}
          Generate 4-6 milestones. 1-3 weeks each. Total weeks proportional to budget (roughly 1 week per 50k budget).`,
        },
        {
          role: 'user',
          content: `Create project plan for: ${project.name} | Client: ${project.client} | Description: ${project.description || 'Software project'} | Value: ${project.value} | Service: ${lead.service_interest || 'Custom Software'}`,
        },
      ],
      temperature: 0.5,
      maxTokens: 2048,
    })

    // Parse AI plan
    let plan: { milestones: any[]; techStack: string[]; estimatedWeeks: number }
    try {
      const cleaned = aiResponse.content.replace(/```json\s*/g, '').replace(/```\s*/g, '').trim()
      plan = JSON.parse(cleaned)
    } catch {
      plan = {
        milestones: [
          { title: 'Sprint 1: Planning & Design', description: 'Architecture, design, project setup', weeks: 2, tasks: ['Requirements', 'Architecture', 'Design'] },
          { title: 'Sprint 2: Core Development', description: 'Core features and API', weeks: 3, tasks: ['Backend', 'Frontend', 'Database'] },
          { title: 'Sprint 3: Testing & Polish', description: 'QA, testing, deployment prep', weeks: 2, tasks: ['Testing', 'Optimization', 'Deployment setup'] },
          { title: 'Sprint 4: Launch', description: 'Deployment and handover', weeks: 1, tasks: ['Deploy', 'Docs', 'Handover'] },
        ],
        techStack: ['React', 'Node.js', 'PostgreSQL'],
        estimatedWeeks: 8,
      }
    }

    // 2. Create GitHub repo (if configured)
    let repoName = ''
    let repoUrl = ''
    const repoSlug = project.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 50)

    if (isGitHubConfigured()) {
      const repo = await createRepo({
        name: repoSlug,
        description: `${project.name} — ${project.client}. Managed by Nexify AI.`,
        private: false,
      })
      if (repo.data) {
        repoName = repo.data.name
        repoUrl = repo.data.html_url
        const readme = `# ${project.name}\n**Client:** ${project.client}\n**Managed by:** Nexify AI Agents\n\n## Milestones\n${plan.milestones.map((m: any) => `### ${m.title} (${m.weeks}w)\n${m.description}\n${m.tasks.map((t: string) => `- [ ] ${t}`).join('\n')}`).join('\n\n')}\n\n## Tech Stack\n${plan.techStack.map((t: string) => `- ${t}`).join('\n')}\n\n---\n*Generated by Nexify AI Agents*`
        await createFile({ repo: repoName, path: 'README.md', content: readme, message: 'Project setup by Nexify AI' })
      }
    }

    // 3. Update project
    db.prepare(`UPDATE projects SET github_repo=?, github_url=?, tech_stack=?, progress=5, updated_at=datetime('now') WHERE id=?`)
      .run(repoName, repoUrl, JSON.stringify(plan.techStack), projectId)

    // 4. Create milestones
    const insertMs = db.prepare(`INSERT INTO milestones (id, project_id, title, description, due_date, status, progress, order_index) VALUES (?,?,?,?,?,'pending',0,?)`)
    const now = new Date()
    plan.milestones.forEach((m: any, i: number) => {
      const due = new Date(now)
      due.setDate(due.getDate() + (m.weeks || 2) * 7)
      insertMs.run(`MS-${Date.now().toString(36)}-${i}`, projectId, m.title, m.description, due.toISOString().split('T')[0], i)
    })

    // 5. Log update
    db.prepare(`INSERT INTO project_updates (id, project_id, message, type) VALUES (?,?,?,'update')`)
      .run(`PU-${Date.now()}`, projectId, `Project started with ${plan.milestones.length} milestones over ~${plan.estimatedWeeks} weeks.${repoUrl ? ' GitHub: ' + repoUrl : ''}`)

    return { success: true }
  } catch (err: any) {
    return { success: false, error: err.message }
  }
}
