import type { NavItem, SearchResult } from '@/types'

export const siteConfig = {
  name: 'Nexify Technologies',
  tagline: "Engineering Tomorrow's Digital Frontiers",
  description: 'AI-powered software development company building next-gen digital products. Custom software, AI solutions, mobile apps, and SaaS products by intelligent AI agents.',
  url: 'https://nexify.tech',
  ogImage: '/images/og.jpg',
  links: {
    twitter: 'https://twitter.com/nexifytech',
    linkedin: 'https://linkedin.com/company/nexifytech',
    github: 'https://github.com/nexifytech',
  },
  contact: {
    email: 'hello@nexify.tech',
    phone: '+91 9373955349',
    location: 'Pune, Maharashtra, India · Remote-First',
  },
} as const

export const navigation: NavItem[] = [
  { name: 'Home', href: '/' },
  { name: 'Services', href: '/services' },
  { name: 'Products', href: '/products' },
  { name: 'Portfolio', href: '/portfolio' },
  { name: 'Pricing', href: '/pricing' },
  { name: 'About', href: '/about' },
  { name: 'Agents', href: '/agents' },
  {
    name: 'Resources', href: '#', hasDropdown: true,
    children: [
      { name: 'Blog', href: '/blog' },
      { name: 'Case Studies', href: '/case-studies' },
      { name: 'Documentation', href: '/docs' },
      { name: 'FAQ', href: '/faq' },
      { name: 'Careers', href: '/careers' },
      { name: 'Industries', href: '/industries' },
      { name: 'Testimonials', href: '/testimonials' },
    ],
  },
  {
    name: 'More', href: '#', hasDropdown: true,
    children: [
      { name: 'Marketing', href: '/marketing' },
      { name: 'Finance', href: '/finance' },
      { name: 'HR', href: '/hr' },
      { name: 'Tech Stack', href: '/techstack' },
      { name: 'AI Automation', href: '/ai-automation' },
      { name: 'Business Automation', href: '/business-automation' },
      { name: 'Dashboards', href: '/dashboards' },
      { name: 'SOPs', href: '/sops' },
      { name: 'Branding', href: '/branding' },
      { name: 'Growth Roadmap', href: '/growth' },
      { name: 'Admin Panel', href: '/admin' },
      { name: 'Client Portal', href: '/portal' },
      { name: 'Sales System', href: '/sales' },
    ],
  },
  { name: 'Contact', href: '/contact' },
]

export const searchData: SearchResult[] = [
  { title: 'Home', href: '/', category: 'Page', icon: 'LayoutDashboard' },
  { title: 'Services', href: '/services', category: 'Page', icon: 'Cpu' },
  { title: 'Products', href: '/products', category: 'Page', icon: 'Zap' },
  { title: 'Portfolio', href: '/portfolio', category: 'Page', icon: 'FolderKanban' },
  { title: 'Pricing', href: '/pricing', category: 'Page', icon: 'DollarSign' },
  { title: 'About Us', href: '/about', category: 'Page', icon: 'Users' },
  { title: 'Blog', href: '/blog', category: 'Page', icon: 'FileText' },
  { title: 'Careers', href: '/careers', category: 'Page', icon: 'Target' },
  { title: 'FAQ', href: '/faq', category: 'Page', icon: 'MessageCircle' },
  { title: 'Contact', href: '/contact', category: 'Page', icon: 'Globe' },
  { title: 'Client Portal', href: '/portal', category: 'System', icon: 'LayoutDashboard' },
  { title: 'Admin Panel', href: '/admin', category: 'System', icon: 'Shield' },
  { title: 'Sales System', href: '/sales', category: 'System', icon: 'TrendingUp' },
  { title: 'Case Studies', href: '/case-studies', category: 'Page', icon: 'FileText' },
  { title: 'Industries', href: '/industries', category: 'Page', icon: 'Globe' },
  { title: 'Testimonials', href: '/testimonials', category: 'Page', icon: 'MessageCircle' },
  { title: 'Documentation', href: '/docs', category: 'Info', icon: 'FileText' },
  { title: 'Finance', href: '/finance', category: 'Info', icon: 'DollarSign' },
  { title: 'HR', href: '/hr', category: 'Info', icon: 'Users' },
  { title: 'Tech Stack', href: '/techstack', category: 'Info', icon: 'Cpu' },
  { title: 'AI Automation', href: '/ai-automation', category: 'Info', icon: 'Brain' },
  { title: 'Dashboards', href: '/dashboards', category: 'Info', icon: 'BarChart3' },
  { title: 'SOPs', href: '/sops', category: 'Info', icon: 'FileText' },
  { title: 'Branding', href: '/branding', category: 'Info', icon: 'Palette' },
  { title: 'Growth Roadmap', href: '/growth', category: 'Info', icon: 'TrendingUp' },
  { title: 'Marketing', href: '/marketing', category: 'Info', icon: 'Globe' },
  { title: 'Operations', href: '/ops', category: 'Info', icon: 'Clock' },
  { title: 'Custom Software Development', href: '/services', category: 'Service', icon: 'Cpu' },
  { title: 'Web Development', href: '/services', category: 'Service', icon: 'Globe' },
  { title: 'Mobile App Development', href: '/services', category: 'Service', icon: 'Smartphone' },
  { title: 'AI Solutions', href: '/services', category: 'Service', icon: 'Brain' },
  { title: 'Data Analytics', href: '/services', category: 'Service', icon: 'BarChart3' },
  { title: 'UI/UX Design', href: '/services', category: 'Service', icon: 'Palette' },
  { title: 'Cloud & DevOps', href: '/services', category: 'Service', icon: 'Cloud' },
  { title: 'AI Chatbots', href: '/services', category: 'Service', icon: 'MessageCircle' },
  { title: 'FlowSprint', href: '/products', category: 'Product', icon: 'KanbanSquare' },
  { title: 'PulseAI', href: '/products', category: 'Product', icon: 'Activity' },
  { title: 'DeskFlow', href: '/products', category: 'Product', icon: 'Headphones' },
  { title: 'SignFlow', href: '/products', category: 'Product', icon: 'FileSignature' },
  { title: 'BotForge', href: '/products', category: 'Product', icon: 'Bot' },
]
