// ============================================================================
// Delivery Start — AI project plan + GitHub repo creation
// Called when a proposal is accepted. Generates milestones, creates repo.
// ============================================================================

import { NextResponse } from 'next/server'
import { getDb } from '@/lib/db'
import { getLead } from '@/lib/db/queries'
import { complete } from '@/lib/ai/providers/client'
import { createRepo, createFile, isGitHubConfigured } from '@/lib/github'

export const dynamic = 'force-dynamic'

export async function POST(request: Request) {
  try {
    const { projectId } = await request.json()
    if (!projectId) return NextResponse.json({ error: 'projectId required' }, { status: 400 })

    const db = getDb()
    const project = db.prepare('SELECT * FROM projects WHERE id = ?').get(projectId) as any
    if (!project) return NextResponse.json({ error: 'Project not found' }, { status: 404 })

    const lead = project.lead_id ? getLead(project.lead_id) : null

    // 1. AI generates project plan
    const aiResponse = await complete({
      messages: [
        {
          role: 'system',
          content: `You are Dev-Alpha, the senior full-stack engineer at Nexify. Generate a detailed project plan with milestones and tasks.

          Return valid JSON only (no markdown, no code blocks):
          {
            "milestones": [
              {
                "title": "Sprint 1: Foundation",
                "description": "Project setup, architecture, CI/CD",
                "weeks": 2,
                "tasks": ["Initialize project", "Set up database schema", "Configure CI/CD pipeline"]
              }
            ],
            "techStack": ["React", "Node.js"],
            "estimatedWeeks": 8
          }

          Generate 4-6 milestones. Each milestone should be 1-3 weeks. Total project time should match the budget (roughly 1 week per 50k).`,
        },
        {
          role: 'user',
          content: `Create a project plan for:
          Project: ${project.name}
          Client: ${project.client}
          Description: ${project.description || 'Software development project'}
          Value: ${project.value}
          ${lead ? `Service: ${lead.service_interest}` : ''}`,
        },
      ],
      temperature: 0.5,
      maxTokens: 2048,
    })

    // Parse AI response
    let plan: { milestones: any[]; techStack: string[]; estimatedWeeks: number }
    try {
      // Extract JSON from response (handle potential markdown wrapping)
      const cleaned = aiResponse.content.replace(/```json\s*/g, '').replace(/```\s*/g, '').trim()
      plan = JSON.parse(cleaned)
    } catch {
      // Fallback plan if AI returns invalid JSON
      plan = {
        milestones: [
          { title: 'Sprint 1: Planning & Design', description: 'Requirements, architecture, UI/UX design', weeks: 2, tasks: ['Requirements gathering', 'System architecture', 'UI/UX design'] },
          { title: 'Sprint 2: Core Development', description: 'Core features and API development', weeks: 3, tasks: ['Backend API development', 'Frontend components', 'Database integration'] },
          { title: 'Sprint 3: Testing & Polish', description: 'QA, testing, deployment prep', weeks: 2, tasks: ['Integration testing', 'Performance optimization', 'Deployment setup'] },
          { title: 'Sprint 4: Launch', description: 'Deployment and handover', weeks: 1, tasks: ['Production deployment', 'Documentation', 'Client handover'] },
        ],
        techStack: ['React', 'Node.js', 'PostgreSQL'],
        estimatedWeeks: 8,
      }
    }

    // 2. Create GitHub repo (if configured)
    let repoName = ''
    let repoUrl = ''
    const repoSlug = project.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 50)

    if (isGitHubConfigured()) {
      const repo = await createRepo({
        name: repoSlug,
        description: `${project.name} — ${project.client}. Nexify AI-managed project.`,
        private: false,
      })

      if (repo.data) {
        repoName = repo.data.name
        repoUrl = repo.data.html_url

        // Push README with project plan
        const readmeContent = `# ${project.name}

**Client:** ${project.client}
**Status:** 🚀 In Progress
**Managed by:** Nexify AI Agents

## Project Plan

${plan.milestones.map((m: any, i: number) =>
  `### ${m.title} (${m.weeks} week${m.weeks > 1 ? 's' : ''})
  ${m.description}
  ${m.tasks.map((t: string) => `- [ ] ${t}`).join('\n  ')}`
).join('\n\n')}

## Tech Stack
${plan.techStack.map((t: string) => `- ${t}`).join('\n')}

---
*Generated by Nexify AI Agents — Zero humans involved.*`

        await createFile({
          repo: repoName,
          path: 'README.md',
          content: readmeContent,
          message: 'Initial project setup by Nexify AI',
        })
      }
    }

    // 3. Update project in DB
    db.prepare(`
      UPDATE projects SET github_repo = ?, github_url = ?, tech_stack = ?, updated_at = datetime('now')
      WHERE id = ?
    `).run(repoName, repoUrl, JSON.stringify(plan.techStack), projectId)

    // 4. Create milestones in DB
    const insertMilestone = db.prepare(`
      INSERT INTO milestones (id, project_id, title, description, due_date, status, progress, order_index)
      VALUES (?, ?, ?, ?, ?, 'pending', 0, ?)
    `)

    const now = new Date()
    plan.milestones.forEach((m: any, i: number) => {
      const due = new Date(now)
      due.setDate(due.getDate() + (m.weeks || 2) * 7)
      const mid = `MS-${Date.now().toString(36).toUpperCase()}-${i}`
      insertMilestone.run(mid, projectId, m.title, m.description, due.toISOString().split('T')[0], i)
    })

    // 5. Log project update
    db.prepare(`
      INSERT INTO project_updates (id, project_id, message, type)
      VALUES (?, ?, ?, 'update')
    `).run(`PU-${Date.now()}`, projectId, `Project plan generated with ${plan.milestones.length} milestones. ${repoUrl ? 'GitHub repo created: ' + repoUrl : 'GitHub not configured — set GITHUB_TOKEN to enable auto-repo creation.'}`)

    return NextResponse.json({
      success: true,
      projectId,
      milestones: plan.milestones.length,
      estimatedWeeks: plan.estimatedWeeks,
      repo: repoUrl || null,
      message: repoUrl
        ? `Project started! ${plan.milestones.length} milestones planned. GitHub repo created at ${repoUrl}`
        : `Project plan ready with ${plan.milestones.length} milestones.`,
    })
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 })
  }
}
