// ============================================================================
// Nexify — Email Service (Resend)
// Free tier: 100 emails/day, no credit card required
// Sign up at https://resend.com
// ============================================================================

import { Resend } from 'resend'

const RESEND_API_KEY = process.env.RESEND_API_KEY || ''
const FROM_EMAIL = process.env.RESEND_FROM_EMAIL || 'onboarding@resend.dev'

let resend: Resend | null = null

function getClient(): Resend | null {
  if (!RESEND_API_KEY) return null
  if (!resend) resend = new Resend(RESEND_API_KEY)
  return resend
}

export interface EmailOptions {
  to: string
  subject: string
  html: string
}

export async function sendEmail(options: EmailOptions): Promise<{ success: boolean; error?: string }> {
  const client = getClient()
  if (!client) {
    console.warn('[Email] RESEND_API_KEY not set. Email not sent.')
    return { success: false, error: 'Email service not configured' }
  }

  try {
    const result = await client.emails.send({
      from: FROM_EMAIL,
      to: options.to,
      subject: options.subject,
      html: options.html,
    })
    return { success: true }
  } catch (err: any) {
    console.error('[Email] Failed to send:', err.message)
    return { success: false, error: err.message }
  }
}

// ── Template: Magic Link ──

export function magicLinkEmail(link: string): string {
  return `
    <div style="font-family: system-ui, sans-serif; max-width: 480px; margin: 0 auto; padding: 24px;">
      <div style="text-align: center; margin-bottom: 24px;">
        <div style="width: 48px; height: 48px; border-radius: 12px; background: linear-gradient(135deg, #3B82F6, #8B5CF6); display: flex; align-items: center; justify-content: center; margin: 0 auto 12px;">
          <span style="color: white; font-size: 20px; font-weight: bold;">N</span>
        </div>
        <h1 style="font-size: 24px; font-weight: 700; color: #0F172A; margin: 0;">Sign in to Nexify Portal</h1>
      </div>
      <p style="color: #475569; font-size: 16px; line-height: 1.5;">Click the link below to sign in to your client portal. This link expires in 30 minutes.</p>
      <div style="text-align: center; margin: 32px 0;">
        <a href="${link}" style="display: inline-block; padding: 14px 32px; background: linear-gradient(135deg, #3B82F6, #8B5CF6); color: white; text-decoration: none; border-radius: 12px; font-size: 16px; font-weight: 600;">
          Sign in to Portal
        </a>
      </div>
      <p style="color: #94A3B8; font-size: 14px;">If you didn't request this, you can safely ignore this email.</p>
      <hr style="border: none; border-top: 1px solid #E2E8F0; margin: 24px 0;" />
      <p style="color: #94A3B8; font-size: 12px;">Nexify Technologies · AI-Native Software Company</p>
    </div>
  `
}

// ── Template: Proposal Ready ──

export function proposalReadyEmail(leadName: string, proposalTitle: string, portalLink: string): string {
  return `
    <div style="font-family: system-ui, sans-serif; max-width: 480px; margin: 0 auto; padding: 24px;">
      <div style="text-align: center; margin-bottom: 24px;">
        <div style="width: 48px; height: 48px; border-radius: 12px; background: linear-gradient(135deg, #3B82F6, #8B5CF6); display: flex; align-items: center; justify-content: center; margin: 0 auto 12px;">
          <span style="color: white; font-size: 20px; font-weight: bold;">N</span>
        </div>
        <h1 style="font-size: 24px; font-weight: 700; color: #0F172A; margin: 0;">Your Proposal is Ready</h1>
      </div>
      <p style="color: #475569; font-size: 16px; line-height: 1.5;">Hi ${leadName},</p>
      <p style="color: #475569; font-size: 16px; line-height: 1.5;">Your proposal <strong>${proposalTitle}</strong> has been generated by our AI agents. Click below to view it in your portal.</p>
      <div style="text-align: center; margin: 32px 0;">
        <a href="${portalLink}" style="display: inline-block; padding: 14px 32px; background: linear-gradient(135deg, #3B82F6, #8B5CF6); color: white; text-decoration: none; border-radius: 12px; font-size: 16px; font-weight: 600;">
          View Proposal
        </a>
      </div>
      <p style="color: #94A3B8; font-size: 14px;">Or copy this link: ${portalLink}</p>
      <hr style="border: none; border-top: 1px solid #E2E8F0; margin: 24px 0;" />
      <p style="color: #94A3B8; font-size: 12px;">Nexify Technologies · AI-Native Software Company</p>
    </div>
  `
}

// ── Template: Payment Receipt ──

export function paymentReceiptEmail(clientName: string, amount: string, invoiceId: string): string {
  return `
    <div style="font-family: system-ui, sans-serif; max-width: 480px; margin: 0 auto; padding: 24px;">
      <h1 style="font-size: 24px; font-weight: 700; color: #0F172A;">Payment Received</h1>
      <p style="color: #475569; font-size: 16px;">Thank you ${clientName}! We've received your payment of <strong>${amount}</strong> for invoice ${invoiceId}.</p>
      <p style="color: #475569; font-size: 16px;">Our AI agents will begin work immediately.</p>
      <hr style="border: none; border-top: 1px solid #E2E8F0; margin: 24px 0;" />
      <p style="color: #94A3B8; font-size: 12px;">Nexify Technologies · AI-Native Software Company</p>
    </div>
  `
}
