// ============================================================================
// Nexify — Agent Library & Marketplace Data
// 500+ AI Agent catalog with categories, implementations, and metadata
// ============================================================================

export type AgentCategory =
  | 'research' | 'coding' | 'data' | 'content' | 'communication'
  | 'finance' | 'healthcare' | 'legal' | 'marketing' | 'sales'
  | 'support' | 'devops' | 'security' | 'hr' | 'productivity'
  | 'education' | 'ecommerce' | 'social' | 'travel' | 'analytics'

export type AgentFramework = 'langgraph' | 'crewai' | 'autogen' | 'agno' | 'llamaindex' | 'custom'
export type AgentStatus = 'active' | 'beta' | 'coming-soon'
export type AgentPricing = 'free' | 'starter' | 'pro' | 'enterprise'

export interface AgentDefinition {
  id: string
  name: string
  slug: string
  description: string
  longDescription: string
  category: AgentCategory
  subcategory: string
  framework: AgentFramework
  status: AgentStatus
  pricing: AgentPricing
  industry: string[]
  version: string
  author: string
  model: string
  tools: string[]
  memory: boolean
  knowledgeBase: boolean
  mcpCompatible: boolean
  apis: string[]
  costEstimate: string
  latencyEstimate: string
  securityLevel: 'low' | 'medium' | 'high'
  featured: boolean
  trending: boolean
  rating: number
  downloads: number
  workflows: string[]
  promptTemplate: string
  systemPrompt: string
  exampleConversation: string[]
  deploymentStatus: 'ready' | 'configuring' | 'requires-setup'
  setupCommands: string[]
}

export const agentCatalog: AgentDefinition[] = [
  // ── RESEARCH CATEGORY ──
  {
    id: 'agent-001',
    name: 'Web Research Agent',
    slug: 'web-research-agent',
    description: 'Searches the web for any topic and synthesizes structured research reports with citations.',
    longDescription: 'A powerful multi-step research agent that uses Tavily search and GPT-4o to gather, analyze, and synthesize web information into comprehensive structured reports. Supports follow-up questions, source verification, and customizable report formats.',
    category: 'research',
    subcategory: 'Web Research',
    framework: 'langgraph',
    status: 'active',
    pricing: 'free',
    industry: ['General', 'Consulting', 'Education', 'Media'],
    version: '2.1.0',
    author: 'Nexify AI',
    model: 'GPT-4o-mini',
    tools: ['web_search', 'content_extract', 'source_verify', 'report_generator'],
    memory: true,
    knowledgeBase: false,
    mcpCompatible: true,
    apis: ['Tavily', 'OpenAI', 'Serper'],
    costEstimate: '$0.05/run',
    latencyEstimate: '8-15s',
    securityLevel: 'low',
    featured: true,
    trending: true,
    rating: 4.8,
    downloads: 12540,
    workflows: ['Research → Synthesize → Report', 'Query → Search → Extract → Format'],
    promptTemplate: 'Research the following topic thoroughly: {{query}}. Provide a structured report with summary, key findings, and sources.',
    systemPrompt: 'You are an expert research assistant. Conduct thorough web research and synthesize findings into clear, structured reports. Always cite sources.',
    exampleConversation: ['User: Research the latest AI chip developments', 'Agent: Here is my comprehensive report on AI chip developments...'],
    deploymentStatus: 'ready',
    setupCommands: ['pip install langchain tavily-python openai', 'export TAVILY_API_KEY=...', 'python agent.py --query "topic"'],
  },
  {
    id: 'agent-002',
    name: 'Competitive Analysis Agent',
    slug: 'competitive-analysis-agent',
    description: 'Analyzes competitors, market positioning, and generates strategic insights from public data.',
    longDescription: 'An advanced competitive intelligence agent that monitors competitor websites, reviews, social media, and news to produce actionable market analysis reports with SWOT frameworks and strategic recommendations.',
    category: 'research',
    subcategory: 'Market Research',
    framework: 'langgraph',
    status: 'active',
    pricing: 'pro',
    industry: ['SaaS', 'E-commerce', 'Consulting', 'Finance'],
    version: '1.8.0',
    author: 'Nexify AI',
    model: 'GPT-4o',
    tools: ['web_search', 'scraper', 'social_monitor', 'swot_generator', 'report_builder'],
    memory: true,
    knowledgeBase: true,
    mcpCompatible: true,
    apis: ['Tavily', 'OpenAI', 'SocialData'],
    costEstimate: '$0.15/run',
    latencyEstimate: '30-60s',
    securityLevel: 'medium',
    featured: true,
    trending: false,
    rating: 4.7,
    downloads: 8900,
    workflows: ['Competitor Scan → Analysis → SWOT → Report'],
    promptTemplate: 'Analyze {{competitor_name}} in the {{industry}} market. Include strengths, weaknesses, opportunities, and threats.',
    systemPrompt: 'You are a competitive intelligence analyst. Research thoroughly and provide unbiased, data-driven competitive analysis.',
    exampleConversation: ['User: Analyze Notion in the productivity space', 'Agent: Here is the comprehensive competitive analysis...'],
    deploymentStatus: 'ready',
    setupCommands: ['pip install langchain beautifulsoup4', 'export OPENAI_API_KEY=...'],
  },

  // ── CODING CATEGORY ──
  {
    id: 'agent-003',
    name: 'Code Review Agent',
    slug: 'code-review-agent',
    description: 'Automated code review with best practice checks, security vulnerability detection, and optimization suggestions.',
    longDescription: 'A sophisticated code review agent that analyzes pull requests and codebases for bugs, security issues, performance bottlenecks, style violations, and suggests improvements with detailed explanations.',
    category: 'coding',
    subcategory: 'Code Quality',
    framework: 'autogen',
    status: 'active',
    pricing: 'starter',
    industry: ['Software', 'SaaS', 'Enterprise IT'],
    version: '3.2.0',
    author: 'Nexify AI',
    model: 'GPT-4o',
    tools: ['git', 'static_analysis', 'security_scan', 'linter'],
    memory: true,
    knowledgeBase: true,
    mcpCompatible: true,
    apis: ['GitHub', 'GitLab', 'OpenAI'],
    costEstimate: '$0.10/review',
    latencyEstimate: '15-30s',
    securityLevel: 'high',
    featured: true,
    trending: true,
    rating: 4.9,
    downloads: 23400,
    workflows: ['PR → Analyze → Report → Suggest Fixes'],
    promptTemplate: 'Review the following code changes. Check for: bugs, security issues, performance, style violations, and test coverage.',
    systemPrompt: 'You are a senior software engineer performing code review. Be thorough, constructive, and specific in your feedback.',
    exampleConversation: ['User: Review this PR for the auth module', 'Agent: Found 3 issues: 1 SQL injection vulnerability, 2 performance optimizations...'],
    deploymentStatus: 'ready',
    setupCommands: ['npm install -g nexify-code-review', 'nexify-code-review --pr=123'],
  },
  {
    id: 'agent-004',
    name: 'Unit Test Generator',
    slug: 'unit-test-generator',
    description: 'Automatically generates comprehensive unit tests with edge case coverage from source code.',
    longDescription: 'An intelligent test generation agent that reads your source code and produces complete test suites with Jest, PyTest, or Vitest. Covers happy paths, edge cases, error states, and boundary conditions.',
    category: 'coding',
    subcategory: 'Testing',
    framework: 'autogen',
    status: 'active',
    pricing: 'starter',
    industry: ['Software', 'SaaS'],
    version: '2.5.0',
    author: 'Nexify AI',
    model: 'GPT-4o-mini',
    tools: ['file_system', 'static_analysis', 'test_runner'],
    memory: false,
    knowledgeBase: false,
    mcpCompatible: true,
    apis: ['OpenAI', 'GitHub'],
    costEstimate: '$0.03/file',
    latencyEstimate: '5-15s',
    securityLevel: 'low',
    featured: false,
    trending: false,
    rating: 4.5,
    downloads: 15600,
    workflows: ['Source → Analyze → Generate Tests → Validate'],
    promptTemplate: 'Generate comprehensive unit tests for the following {{language}} code. Include edge cases and error handling.',
    systemPrompt: 'You are an expert QA engineer. Generate thorough, production-quality unit tests with maximum coverage.',
    exampleConversation: ['User: Generate tests for this React component', 'Agent: Created 12 tests covering render states, user interactions, error handling...'],
    deploymentStatus: 'ready',
    setupCommands: ['pip install nexify-test-gen', 'nexify-test-gen --path=./src'],
  },
  {
    id: 'agent-005',
    name: 'SQL Query Agent',
    slug: 'sql-query-agent',
    description: 'Converts natural language to optimized SQL queries with schema understanding and query explanations.',
    longDescription: 'A database-savvy agent that understands your schema, writes complex SQL queries from natural language requests, optimizes them for performance, and explains the results in plain English.',
    category: 'coding',
    subcategory: 'Database',
    framework: 'langgraph',
    status: 'active',
    pricing: 'starter',
    industry: ['Data', 'Finance', 'SaaS', 'Enterprise'],
    version: '2.0.0',
    author: 'Nexify AI',
    model: 'GPT-4o',
    tools: ['schema_reader', 'query_executor', 'query_optimizer', 'visualizer'],
    memory: true,
    knowledgeBase: true,
    mcpCompatible: true,
    apis: ['PostgreSQL', 'MySQL', 'BigQuery', 'Snowflake', 'OpenAI'],
    costEstimate: '$0.08/query',
    latencyEstimate: '3-8s',
    securityLevel: 'high',
    featured: false,
    trending: true,
    rating: 4.6,
    downloads: 11200,
    workflows: ['NL Request → Schema → SQL → Optimize → Execute → Explain'],
    promptTemplate: 'Convert this request to SQL: {{query}}. The database schema is: {{schema}}.',
    systemPrompt: 'You are a DBA and SQL expert. Write efficient, correct SQL queries and explain them clearly.',
    exampleConversation: ['User: Show me monthly revenue growth for 2026', 'Agent: SELECT DATE_TRUNC... Here is the query and result explanation...'],
    deploymentStatus: 'ready',
    setupCommands: ['pip install nexify-sql-agent', 'nexify-sql-agent --init'],
  },

  // ── CONTENT CATEGORY ──
  {
    id: 'agent-006',
    name: 'Documentation Writer',
    slug: 'documentation-writer',
    description: 'Generates comprehensive technical documentation, API docs, and user guides from source code.',
    longDescription: 'An advanced documentation agent that analyzes your codebase, API endpoints, and components to produce professional documentation with examples, diagrams, and interactive references.',
    category: 'content',
    subcategory: 'Technical Writing',
    framework: 'llamaindex',
    status: 'active',
    pricing: 'free',
    industry: ['Software', 'SaaS', 'Enterprise'],
    version: '2.8.0',
    author: 'Nexify AI',
    model: 'GPT-4o-mini',
    tools: ['file_system', 'code_analyzer', 'markdown_generator'],
    memory: true,
    knowledgeBase: true,
    mcpCompatible: true,
    apis: ['OpenAI', 'GitHub'],
    costEstimate: '$0.05/doc',
    latencyEstimate: '10-25s',
    securityLevel: 'low',
    featured: false,
    trending: false,
    rating: 4.4,
    downloads: 7800,
    workflows: ['Code → Analyze → Outline → Write → Format'],
    promptTemplate: 'Generate documentation for the following code: {{code}}. Include: description, parameters, return values, examples.',
    systemPrompt: 'You are a technical writer. Create clear, comprehensive documentation that developers love to read.',
    exampleConversation: ['User: Document my API endpoints', 'Agent: Here is complete API documentation with 20 endpoints...'],
    deploymentStatus: 'ready',
    setupCommands: ['npm install -g nexify-docs', 'nexify-docs --watch'],
  },
  {
    id: 'agent-007',
    name: 'Meeting Notes Agent',
    slug: 'meeting-notes-agent',
    description: 'Transcribes, summarizes, and extracts action items from meeting recordings with speaker diarization.',
    longDescription: 'A meeting intelligence agent that joins your calls, transcribes in real-time, generates structured notes, extracts action items and decisions, and integrates with your calendar and task management tools.',
    category: 'content',
    subcategory: 'Meeting Intelligence',
    framework: 'agno',
    status: 'active',
    pricing: 'pro',
    industry: ['General', 'Consulting', 'SaaS', 'Enterprise'],
    version: '1.5.0',
    author: 'Nexify AI',
    model: 'GPT-4o',
    tools: ['audio_transcriber', 'speaker_diarizer', 'summarizer', 'calendar_api', 'task_creator'],
    memory: true,
    knowledgeBase: false,
    mcpCompatible: true,
    apis: ['OpenAI Whisper', 'Google Calendar', 'Slack', 'Notion'],
    costEstimate: '$0.20/meeting',
    latencyEstimate: '2x meeting duration',
    securityLevel: 'high',
    featured: false,
    trending: true,
    rating: 4.7,
    downloads: 6500,
    workflows: ['Audio → Transcribe → Diarize → Summarize → Extract Actions → Sync'],
    promptTemplate: 'Summarize this meeting transcript. Extract: key decisions, action items, owners, deadlines, and follow-ups.',
    systemPrompt: 'You are a meeting intelligence assistant. Capture every decision, action item, and important detail accurately.',
    exampleConversation: ['User: Process this 30-min engineering meeting', 'Agent: Generated notes with 5 decisions, 12 action items, and 3 blockers...'],
    deploymentStatus: 'ready',
    setupCommands: ['npm install nexify-meeting-agent', 'nexify-meeting --config'],
  },
  {
    id: 'agent-008',
    name: 'News Summarizer Agent',
    slug: 'news-summarizer-agent',
    description: 'Curates and summarizes news from multiple sources with topic clustering and sentiment analysis.',
    longDescription: 'A personalized news intelligence agent that monitors RSS feeds, news APIs, and publications. It deduplicates stories, clusters related topics, analyzes sentiment, and delivers a daily briefing tailored to your interests.',
    category: 'content',
    subcategory: 'News Intelligence',
    framework: 'langgraph',
    status: 'active',
    pricing: 'free',
    industry: ['Media', 'Finance', 'Consulting', 'General'],
    version: '1.3.0',
    author: 'Nexify AI',
    model: 'GPT-4o-mini',
    tools: ['rss_reader', 'web_scraper', 'deduplicator', 'sentiment_analyzer', 'summary_generator'],
    memory: true,
    knowledgeBase: true,
    mcpCompatible: true,
    apis: ['NewsAPI', 'RSS', 'OpenAI'],
    costEstimate: '$0.02/briefing',
    latencyEstimate: '5-10s',
    securityLevel: 'low',
    featured: false,
    trending: false,
    rating: 4.3,
    downloads: 9200,
    workflows: ['Feeds → Fetch → Deduplicate → Cluster → Summarize → Brief'],
    promptTemplate: 'Summarize today\'s top news in {{topic}}. Include: key events, perspectives, and market impact.',
    systemPrompt: 'You are a news curator. Provide balanced, accurate news summaries without bias.',
    exampleConversation: ['User: Give me today\'s AI industry news', 'Agent: Here are the top 5 AI stories today with analysis...'],
    deploymentStatus: 'ready',
    setupCommands: ['pip install nexify-news', 'export NEWSAPI_KEY=...'],
  },

  // ── COMMUNICATION CATEGORY ──
  {
    id: 'agent-009',
    name: 'Email Drafting Agent',
    slug: 'email-drafting-agent',
    description: 'Crafts professional emails in any tone, language, and context with smart template suggestions.',
    longDescription: 'An intelligent email composition agent that understands context, recipient relationship, and desired outcome to draft perfect emails. Supports multiple languages, tones, and templates. Integrates with Gmail, Outlook, and custom SMTP.',
    category: 'communication',
    subcategory: 'Email',
    framework: 'agno',
    status: 'active',
    pricing: 'free',
    industry: ['General', 'Sales', 'HR', 'Legal'],
    version: '2.0.0',
    author: 'Nexify AI',
    model: 'GPT-4o',
    tools: ['email_templates', 'tone_analyzer', 'grammar_checker', 'smtp_client'],
    memory: true,
    knowledgeBase: true,
    mcpCompatible: true,
    apis: ['Gmail API', 'Outlook API', 'OpenAI'],
    costEstimate: '$0.01/email',
    latencyEstimate: '2-5s',
    securityLevel: 'medium',
    featured: false,
    trending: false,
    rating: 4.5,
    downloads: 18300,
    workflows: ['Context → Tone Select → Draft → Review → Send'],
    promptTemplate: 'Draft a {{tone}} email to {{recipient}} about {{topic}}. Context: {{context}}.',
    systemPrompt: 'You are a professional email assistant. Craft clear, effective emails that achieve the sender\'s goals.',
    exampleConversation: ['User: Draft a follow-up email to the client about the proposal', 'Agent: Here is a professional follow-up email ready to send...'],
    deploymentStatus: 'ready',
    setupCommands: ['pip install nexify-email', 'nexify-email --configure'],
  },
  {
    id: 'agent-010',
    name: 'Social Media Agent',
    slug: 'social-media-agent',
    description: 'Creates, schedules, and optimizes social media content across platforms with engagement analytics.',
    longDescription: 'A full social media management agent that generates platform-optimized content, schedules posts, analyzes engagement patterns, suggests improvements, and maintains brand voice consistency across LinkedIn, Twitter/X, Instagram, and more.',
    category: 'communication',
    subcategory: 'Social Media',
    framework: 'crewai',
    status: 'active',
    pricing: 'pro',
    industry: ['Marketing', 'SaaS', 'E-commerce', 'Media'],
    version: '3.0.0',
    author: 'Nexify AI',
    model: 'GPT-4o',
    tools: ['content_generator', 'scheduler', 'analytics', 'image_creator', 'hashtag_optimizer'],
    memory: true,
    knowledgeBase: true,
    mcpCompatible: true,
    apis: ['LinkedIn API', 'Twitter API', 'Instagram API', 'OpenAI', 'DALL-E'],
    costEstimate: '$0.08/post',
    latencyEstimate: '5-15s',
    securityLevel: 'medium',
    featured: true,
    trending: true,
    rating: 4.6,
    downloads: 14200,
    workflows: ['Strategy → Create → Optimize → Schedule → Analyze → Iterate'],
    promptTemplate: 'Create a {{platform}} post about {{topic}} for our brand {{brand}}. Tone: {{tone}}. Include: {{elements}}.',
    systemPrompt: 'You are a social media strategist. Create engaging, on-brand content that drives engagement and conversions.',
    exampleConversation: ['User: Create a LinkedIn post about our new AI chatbot service', 'Agent: Here is an optimized LinkedIn post with carousel ideas and hashtags...'],
    deploymentStatus: 'ready',
    setupCommands: ['npm install -g nexify-social', 'nexify-social --connect'],
  },

  // ── DATA CATEGORY ──
  {
    id: 'agent-011',
    name: 'Data Analysis Agent',
    slug: 'data-analysis-agent',
    description: 'Analyzes datasets, generates visualizations, and produces insights with natural language queries.',
    longDescription: 'A powerful data analysis agent that connects to your databases, CSV files, or data warehouses. It understands your schema, answers questions in plain English, generates interactive visualizations, and produces executive-ready reports.',
    category: 'data',
    subcategory: 'Business Intelligence',
    framework: 'llamaindex',
    status: 'active',
    pricing: 'pro',
    industry: ['Finance', 'SaaS', 'Healthcare', 'E-commerce'],
    version: '3.5.0',
    author: 'Nexify AI',
    model: 'GPT-4o',
    tools: ['sql_executor', 'chart_generator', 'statistical_analyzer', 'report_builder'],
    memory: true,
    knowledgeBase: true,
    mcpCompatible: true,
    apis: ['PostgreSQL', 'BigQuery', 'Snowflake', 'OpenAI', 'Chart.js'],
    costEstimate: '$0.12/analysis',
    latencyEstimate: '8-20s',
    securityLevel: 'high',
    featured: true,
    trending: true,
    rating: 4.8,
    downloads: 19600,
    workflows: ['Data → Schema → Analyze → Visualize → Report', 'Query → SQL → Chart → Insight'],
    promptTemplate: 'Analyze this dataset: {{data_description}}. Answer: {{question}}. Include visualizations and key insights.',
    systemPrompt: 'You are a senior data analyst. Provide accurate, insightful analysis with clear visualizations.',
    exampleConversation: ['User: Show me customer churn trends for Q2', 'Agent: Here is the churn analysis with 3 charts and 5 key findings...'],
    deploymentStatus: 'ready',
    setupCommands: ['pip install nexify-data-agent', 'nexify-data --connect'],
  },
  {
    id: 'agent-012',
    name: 'PDF QA Agent',
    slug: 'pdf-qa-agent',
    description: 'Extracts, indexes, and queries PDF documents with citations and page references.',
    longDescription: 'A document intelligence agent that ingests PDF files, builds a searchable knowledge base, and answers questions with precise citations, page numbers, and context. Supports multiple documents, tables, and scanned PDFs via OCR.',
    category: 'data',
    subcategory: 'Document Intelligence',
    framework: 'llamaindex',
    status: 'active',
    pricing: 'starter',
    industry: ['Legal', 'Healthcare', 'Finance', 'Education'],
    version: '2.3.0',
    author: 'Nexify AI',
    model: 'GPT-4o',
    tools: ['pdf_parser', 'ocr', 'vector_index', 'qa_engine', 'citation_generator'],
    memory: true,
    knowledgeBase: true,
    mcpCompatible: true,
    apis: ['OpenAI', 'Pinecone', 'Tesseract'],
    costEstimate: '$0.15/document',
    latencyEstimate: '5-30s depending on size',
    securityLevel: 'high',
    featured: false,
    trending: true,
    rating: 4.7,
    downloads: 21300,
    workflows: ['Upload → Index → Query → Answer with Citations'],
    promptTemplate: 'Answer this question based on the uploaded document: {{question}}. Cite the relevant pages and sections.',
    systemPrompt: 'You are a document analyst. Answer questions accurately using only the provided document content.',
    exampleConversation: ['User: What are the termination clauses in this contract?', 'Agent: According to Section 7.2 on page 14...'],
    deploymentStatus: 'ready',
    setupCommands: ['pip install nexify-pdf-agent', 'nexify-pdf --index'],
  },

  // ── SUPPORT CATEGORY ──
  {
    id: 'agent-013',
    name: 'Customer Support Agent',
    slug: 'customer-support-agent',
    description: '24/7 intelligent support with ticket management, sentiment detection, and human handoff.',
    longDescription: 'An enterprise-grade customer support agent that handles inquiries across email, chat, and social media. Features intelligent routing, sentiment-aware responses, knowledge base integration, escalation management, and detailed analytics.',
    category: 'support',
    subcategory: 'Customer Service',
    framework: 'crewai',
    status: 'active',
    pricing: 'enterprise',
    industry: ['SaaS', 'E-commerce', 'Healthcare', 'Finance'],
    version: '4.0.0',
    author: 'Nexify AI',
    model: 'GPT-4o',
    tools: ['ticket_system', 'sentiment_analyzer', 'kb_search', 'escalation_manager', 'analytics'],
    memory: true,
    knowledgeBase: true,
    mcpCompatible: true,
    apis: ['Zendesk', 'Intercom', 'Slack', 'OpenAI', 'SendGrid'],
    costEstimate: '$0.10/conversation',
    latencyEstimate: '2-5s',
    securityLevel: 'high',
    featured: true,
    trending: true,
    rating: 4.9,
    downloads: 31200,
    workflows: ['Inquiry → Analyze → Respond → Resolve → Learn'],
    promptTemplate: 'Respond to this customer inquiry: {{message}}. Customer context: {{context}}. KB matches: {{kb_results}}.',
    systemPrompt: 'You are a customer support specialist. Be helpful, empathetic, and efficient. Know when to escalate.',
    exampleConversation: ['User: My subscription was charged twice', 'Agent: I apologize for the issue. Let me investigate and resolve this...'],
    deploymentStatus: 'ready',
    setupCommands: ['npm install -g nexify-support', 'nexify-support --configure'],
  },
  {
    id: 'agent-014',
    name: 'GitHub Issue Triager',
    slug: 'github-issue-triager',
    description: 'Automatically triages, labels, prioritizes GitHub issues with smart routing and duplicate detection.',
    longDescription: 'An intelligent issue management agent that monitors GitHub repositories, automatically categorizes and labels issues, detects duplicates, prioritizes by impact, routes to the right team, and suggests resolutions from past issues.',
    category: 'support',
    subcategory: 'Developer Support',
    framework: 'autogen',
    status: 'active',
    pricing: 'starter',
    industry: ['Software', 'SaaS', 'Open Source'],
    version: '2.1.0',
    author: 'Nexify AI',
    model: 'GPT-4o-mini',
    tools: ['github_api', 'labeler', 'duplicate_detector', 'priority_calculator', 'auto_responder'],
    memory: true,
    knowledgeBase: true,
    mcpCompatible: true,
    apis: ['GitHub API', 'OpenAI'],
    costEstimate: '$0.02/issue',
    latencyEstimate: '3-8s',
    securityLevel: 'medium',
    featured: false,
    trending: false,
    rating: 4.4,
    downloads: 5400,
    workflows: ['Issue → Classify → Label → Prioritize → Route → Suggest'],
    promptTemplate: 'Triage this GitHub issue: {{issue}}. Repository: {{repo}}. Check for duplicates, assign priority, and suggest labels.',
    systemPrompt: 'You are an open-source maintainer. Triage issues efficiently, fairly, and helpfully.',
    exampleConversation: ['User: Triage issue #456 about login timeout', 'Agent: Categorized as bug, priority high, routing to auth team...'],
    deploymentStatus: 'ready',
    setupCommands: ['npm install -g nexify-issue-triage', 'nexify-triage --repo=owner/repo'],
  },

  // ── DEVOPS CATEGORY ──
  {
    id: 'agent-015',
    name: 'DevOps Monitoring Agent',
    slug: 'devops-monitoring-agent',
    description: 'Infrastructure monitoring, incident detection, root cause analysis, and automated remediation.',
    longDescription: 'A comprehensive DevOps agent that monitors cloud infrastructure, detects anomalies, performs root cause analysis, and executes automated remediation workflows. Integrates with major cloud providers and monitoring tools.',
    category: 'devops',
    subcategory: 'Infrastructure',
    framework: 'agno',
    status: 'active',
    pricing: 'enterprise',
    industry: ['SaaS', 'Enterprise IT', 'Finance'],
    version: '2.5.0',
    author: 'Nexify AI',
    model: 'GPT-4o',
    tools: ['cloud_monitor', 'log_analyzer', 'alert_handler', 'remediation_executor', 'dashboard_builder'],
    memory: true,
    knowledgeBase: true,
    mcpCompatible: true,
    apis: ['AWS', 'GCP', 'Azure', 'Datadog', 'PagerDuty', 'OpenAI'],
    costEstimate: '$0.20/incident',
    latencyEstimate: '10-30s',
    securityLevel: 'high',
    featured: false,
    trending: false,
    rating: 4.6,
    downloads: 4300,
    workflows: ['Metrics → Anomaly → Alert → Diagnose → Remediate → Report'],
    promptTemplate: 'Analyze this infrastructure incident: {{incident}}. Metrics: {{metrics}}. Logs: {{logs}}. Recommend remediation.',
    systemPrompt: 'You are a senior DevOps engineer. Diagnose incidents accurately and execute remediation efficiently.',
    exampleConversation: ['User: Investigate high CPU on production', 'Agent: Found the cause: memory leak in worker process. Restarting...'],
    deploymentStatus: 'ready',
    setupCommands: ['pip install nexify-devops', 'nexify-devops --init --provider=aws'],
  },
  {
    id: 'agent-016',
    name: 'Security Audit Agent',
    slug: 'security-audit-agent',
    description: 'Automated security scanning, vulnerability assessment, compliance checking, and remediation guidance.',
    longDescription: 'A security-focused agent that scans codebases, dependencies, and infrastructure for vulnerabilities. Checks against OWASP Top 10, CVE databases, and compliance frameworks (SOC 2, HIPAA, GDPR). Provides prioritized remediation plans.',
    category: 'security',
    subcategory: 'Vulnerability Management',
    framework: 'autogen',
    status: 'active',
    pricing: 'enterprise',
    industry: ['Enterprise', 'Finance', 'Healthcare', 'SaaS'],
    version: '3.0.0',
    author: 'Nexify AI',
    model: 'GPT-4o',
    tools: ['vulnerability_scanner', 'dependency_checker', 'compliance_analyzer', 'report_generator'],
    memory: true,
    knowledgeBase: true,
    mcpCompatible: true,
    apis: ['Snyk', 'Trivy', 'OpenAI', 'NVD'],
    costEstimate: '$0.25/scan',
    latencyEstimate: '30-120s',
    securityLevel: 'high',
    featured: false,
    trending: false,
    rating: 4.8,
    downloads: 3200,
    workflows: ['Scan → Analyze → Prioritize → Report → Track'],
    promptTemplate: 'Perform a security audit on: {{target}}. Check for: OWASP Top 10, dependency vulnerabilities, misconfigurations.',
    systemPrompt: 'You are a security engineer. Be thorough, provide actionable fixes, and prioritize by risk level.',
    exampleConversation: ['User: Audit the authentication module', 'Agent: Found 3 vulnerabilities: 1 critical, 2 medium. Here are fixes...'],
    deploymentStatus: 'ready',
    setupCommands: ['npm install -g nexify-security', 'nexify-security --scan'],
  },

  // ── SALES CATEGORY ──
  {
    id: 'agent-017',
    name: 'Sales Lead Qualification Agent',
    slug: 'sales-lead-qualification',
    description: 'Qualifies leads, scores prospects, and generates personalized outreach sequences.',
    longDescription: 'A sales intelligence agent that researches prospects, scores leads based on fit and intent, generates personalized outreach sequences, and schedules meetings. Integrates with CRM to track the full lead lifecycle.',
    category: 'sales',
    subcategory: 'Lead Generation',
    framework: 'crewai',
    status: 'active',
    pricing: 'pro',
    industry: ['SaaS', 'Enterprise', 'Consulting'],
    version: '2.0.0',
    author: 'Nexify AI',
    model: 'GPT-4o',
    tools: ['lead_researcher', 'scoring_engine', 'email_sequencer', 'crm_integrator', 'meeting_scheduler'],
    memory: true,
    knowledgeBase: true,
    mcpCompatible: true,
    apis: ['LinkedIn API', 'HubSpot', 'Salesforce', 'OpenAI', 'Cal.com'],
    costEstimate: '$0.15/lead',
    latencyEstimate: '15-45s',
    securityLevel: 'medium',
    featured: true,
    trending: true,
    rating: 4.7,
    downloads: 8900,
    workflows: ['Lead → Research → Score → Sequence → Book → Track'],
    promptTemplate: 'Qualify this lead: {{lead_info}}. ICP: {{icp}}. Score based on: budget, authority, need, timeline.',
    systemPrompt: 'You are a sales development representative. Qualify leads efficiently and personalize every interaction.',
    exampleConversation: ['User: Qualify this new inbound lead from Acme Corp', 'Agent: Score 85/100. Budget: verified. Authority: CTO. Need: urgent. Recommended action...'],
    deploymentStatus: 'ready',
    setupCommands: ['npm install -g nexify-sales', 'nexify-sales --connect'],
  },

  // ── HR CATEGORY ──
  {
    id: 'agent-018',
    name: 'Resume Parser & Screening Agent',
    slug: 'resume-parser-agent',
    description: 'Parses, screens, and ranks resumes with skill matching and candidate scoring.',
    longDescription: 'An HR intelligence agent that parses resumes in any format, extracts structured data, matches skills against job requirements, ranks candidates, and generates interview questions with evaluation criteria.',
    category: 'hr',
    subcategory: 'Recruitment',
    framework: 'llamaindex',
    status: 'active',
    pricing: 'pro',
    industry: ['HR Tech', 'Enterprise', 'Consulting'],
    version: '2.2.0',
    author: 'Nexify AI',
    model: 'GPT-4o-mini',
    tools: ['resume_parser', 'skill_extractor', 'matching_engine', 'interview_question_generator'],
    memory: false,
    knowledgeBase: true,
    mcpCompatible: true,
    apis: ['OpenAI', 'LinkedIn API'],
    costEstimate: '$0.05/resume',
    latencyEstimate: '3-10s',
    securityLevel: 'high',
    featured: false,
    trending: false,
    rating: 4.5,
    downloads: 6700,
    workflows: ['Resume → Parse → Extract Skills → Match → Score → Rank'],
    promptTemplate: 'Screen this resume: {{resume_text}}. Job requirements: {{job_description}}. Score and rank the candidate.',
    systemPrompt: 'You are an HR screening specialist. Evaluate candidates fairly and thoroughly against job requirements.',
    exampleConversation: ['User: Screen candidate for Senior React Engineer', 'Agent: Score 92/100. Strong match: React, TypeScript, GraphQL. Gaps: none. Recommended: Interview.'],
    deploymentStatus: 'ready',
    setupCommands: ['pip install nexify-hr-agent', 'nexify-hr --screening'],
  },

  // ── FINANCE CATEGORY ──
  {
    id: 'agent-019',
    name: 'Stock Research Agent',
    slug: 'stock-research-agent',
    description: 'Comprehensive stock analysis with financial data, news sentiment, and investment recommendations.',
    longDescription: 'A financial analysis agent that researches stocks using real-time market data, financial statements, news sentiment, and analyst ratings. Generates comprehensive investment reports with buy/sell/hold recommendations and risk assessments.',
    category: 'finance',
    subcategory: 'Investment Research',
    framework: 'langgraph',
    status: 'active',
    pricing: 'pro',
    industry: ['Finance', 'Investment', 'Consulting'],
    version: '1.8.0',
    author: 'Nexify AI',
    model: 'GPT-4o',
    tools: ['market_data', 'financial_analyzer', 'news_sentiment', 'risk_calculator', 'report_generator'],
    memory: true,
    knowledgeBase: true,
    mcpCompatible: true,
    apis: ['Yahoo Finance', 'Alpha Vantage', 'OpenAI'],
    costEstimate: '$0.20/analysis',
    latencyEstimate: '15-40s',
    securityLevel: 'medium',
    featured: false,
    trending: false,
    rating: 4.3,
    downloads: 5800,
    workflows: ['Ticker → Data → Fundamentals → Sentiment → Risk → Report'],
    promptTemplate: 'Research stock {{ticker}}. Analyze: financials, news sentiment, technical indicators, competitive position.',
    systemPrompt: 'You are a financial analyst. Provide objective, data-driven stock analysis with clear risk assessment.',
    exampleConversation: ['User: Analyze AAPL for investment', 'Agent: Hold rating. Strong fundamentals but premium valuation...'],
    deploymentStatus: 'ready',
    setupCommands: ['pip install nexify-stock-agent', 'export ALPHA_VANTAGE_KEY=...'],
  },
  {
    id: 'agent-020',
    name: 'Multi-Agent Debate System',
    slug: 'multi-agent-debate',
    description: 'Multiple AI agents debate topics from different perspectives to reach consensus or highlight disagreements.',
    longDescription: 'An advanced multi-agent system where 3+ AI agents with different personas debate a topic. Each agent argues from a distinct perspective (optimist, pessimist, data-driven, creative, conservative). The system moderates, tracks arguments, and produces a synthesis of the debate.',
    category: 'research',
    subcategory: 'Multi-Agent Systems',
    framework: 'autogen',
    status: 'active',
    pricing: 'pro',
    industry: ['Research', 'Consulting', 'Education', 'Strategy'],
    version: '1.5.0',
    author: 'Nexify AI',
    model: 'GPT-4o',
    tools: ['moderator', 'arguer', 'fact_checker', 'synthesis_engine'],
    memory: true,
    knowledgeBase: true,
    mcpCompatible: true,
    apis: ['OpenAI', 'Anthropic', 'Google AI'],
    costEstimate: '$0.30/debate',
    latencyEstimate: '60-180s',
    securityLevel: 'low',
    featured: true,
    trending: true,
    rating: 4.9,
    downloads: 4100,
    workflows: ['Topic → Assign — Personas → Debate → Fact Check → Synthesize'],
    promptTemplate: 'Debate the topic: {{topic}}. Assign personas: {{personas}}. Discuss: {{aspects}}.',
    systemPrompt: 'You are a debate participant. Argue your assigned position persuasively using facts and logic.',
    exampleConversation: ['User: Debate: should AI be regulated?', 'Agent: Four perspectives debated. Synthesis: regulation needed but balanced...'],
    deploymentStatus: 'ready',
    setupCommands: ['pip install nexify-debate', 'nexify-debate --topic "AI Safety" --personas 4'],
  },
  {
    id: 'agent-021',
    name: 'Job Application Agent',
    slug: 'job-application-agent',
    description: 'Automates job applications with tailored resumes, cover letters, and application tracking.',
    longDescription: 'A career intelligence agent that matches your profile to job openings, tailors your resume and cover letter for each application, tracks application status, and prepares you for interviews with company-specific research.',
    category: 'hr',
    subcategory: 'Career Development',
    framework: 'agno',
    status: 'active',
    pricing: 'starter',
    industry: ['General', 'HR Tech', 'Enterprise'],
    version: '1.3.0',
    author: 'Nexify AI',
    model: 'GPT-4o-mini',
    tools: ['job_matcher', 'resume_tailorer', 'cover_letter_gen', 'application_tracker', 'company_researcher'],
    memory: true,
    knowledgeBase: true,
    mcpCompatible: true,
    apis: ['LinkedIn API', 'Indeed API', 'OpenAI'],
    costEstimate: '$0.08/application',
    latencyEstimate: '10-20s',
    securityLevel: 'high',
    featured: false,
    trending: false,
    rating: 4.2,
    downloads: 3800,
    workflows: ['Job → Match → Tailor → Apply → Track → Prepare'],
    promptTemplate: 'Generate a tailored resume and cover letter for {{job_title}} at {{company}}. My profile: {{profile}}.',
    systemPrompt: 'You are a career coach. Help candidates present their best selves to land the job.',
    exampleConversation: ['User: Apply to Senior AI Engineer at Google', 'Agent: Tailored resume and cover letter generated. Here are interview prep notes...'],
    deploymentStatus: 'ready',
    setupCommands: ['npm install -g nexify-jobs', 'nexify-jobs --profile=resume.pdf'],
  },
  {
    id: 'agent-022',
    name: 'Travel Planner Agent',
    slug: 'travel-planner-agent',
    description: 'End-to-end travel planning with itinerary generation, booking suggestions, and budget optimization.',
    longDescription: 'A comprehensive travel agent that plans complete trips including flights, accommodations, activities, dining, and transportation. Optimizes for budget, preferences, and time constraints. Integrates with booking platforms for real-time availability.',
    category: 'travel',
    subcategory: 'Trip Planning',
    framework: 'langgraph',
    status: 'active',
    pricing: 'free',
    industry: ['Travel', 'Hospitality', 'General'],
    version: '2.0.0',
    author: 'Nexify AI',
    model: 'GPT-4o-mini',
    tools: ['flight_search', 'hotel_search', 'itinerary_builder', 'budget_optimizer', 'weather_checker'],
    memory: true,
    knowledgeBase: false,
    mcpCompatible: true,
    apis: ['Amadeus', 'Google Maps', 'OpenAI', 'Weather API'],
    costEstimate: '$0.05/trip',
    latencyEstimate: '10-25s',
    securityLevel: 'low',
    featured: false,
    trending: false,
    rating: 4.4,
    downloads: 7200,
    workflows: ['Destination → Preferences → Research → Book → Itinerary'],
    promptTemplate: 'Plan a trip to {{destination}} from {{date_from}} to {{date_to}}. Budget: {{budget}}. Preferences: {{preferences}}.',
    systemPrompt: 'You are a travel planning expert. Create memorable, well-organized itineraries that match preferences and budget.',
    exampleConversation: ['User: Plan a 5-day trip to Bali on a budget of $2000', 'Agent: Here is your complete Bali itinerary with flight options...'],
    deploymentStatus: 'ready',
    setupCommands: ['pip install nexify-travel', 'nexify-travel --plan'],
  },
  {
    id: 'agent-023',
    name: 'Recipe & Meal Planning Agent',
    slug: 'recipe-agent',
    description: 'Generates personalized recipes and weekly meal plans based on dietary restrictions and preferences.',
    longDescription: 'A culinary AI agent that creates custom recipes and weekly meal plans based on dietary requirements, available ingredients, nutritional goals, and cuisine preferences. Generates shopping lists and cooking instructions.',
    category: 'productivity',
    subcategory: 'Food & Nutrition',
    framework: 'agno',
    status: 'active',
    pricing: 'free',
    industry: ['Food', 'Health', 'General'],
    version: '1.2.0',
    author: 'Nexify AI',
    model: 'GPT-4o-mini',
    tools: ['recipe_generator', 'nutrition_calculator', 'shopping_list_builder', 'meal_planner'],
    memory: true,
    knowledgeBase: true,
    mcpCompatible: true,
    apis: ['OpenAI', 'Spoonacular'],
    costEstimate: '$0.03/plan',
    latencyEstimate: '5-15s',
    securityLevel: 'low',
    featured: false,
    trending: false,
    rating: 4.1,
    downloads: 5600,
    workflows: ['Preferences → Generate → Plan → Shop → Cook'],
    promptTemplate: 'Create a {{days}}-day meal plan for {{diet}}. Include {{meals}} meals per day. Budget: {{budget}}.',
    systemPrompt: 'You are a personal chef and nutritionist. Create delicious, healthy meals that fit preferences and budget.',
    exampleConversation: ['User: Plan a week of vegan meals', 'Agent: Here is your 7-day vegan meal plan with shopping list...'],
    deploymentStatus: 'ready',
    setupCommands: ['npm install -g nexify-meals', 'nexify-meals --plan'],
  },
  {
    id: 'agent-024',
    name: 'Content Moderation Agent',
    slug: 'content-moderation-agent',
    description: 'Automated content moderation with policy enforcement, toxicity detection, and human escalation.',
    longDescription: 'A content safety agent that scans user-generated content for policy violations, toxicity, spam, and sensitive information. Supports text, image, and video moderation with configurable policies and human-in-the-loop escalation.',
    category: 'security',
    subcategory: 'Content Safety',
    framework: 'agno',
    status: 'active',
    pricing: 'enterprise',
    industry: ['Social Media', 'E-commerce', 'Gaming', 'Education'],
    version: '2.0.0',
    author: 'Nexify AI',
    model: 'GPT-4o',
    tools: ['text_analyzer', 'image_scanner', 'policy_enforcer', 'escalation_manager'],
    memory: false,
    knowledgeBase: true,
    mcpCompatible: true,
    apis: ['OpenAI', 'Google Vision', 'Clarify AI'],
    costEstimate: '$0.01/check',
    latencyEstimate: '1-3s',
    securityLevel: 'high',
    featured: false,
    trending: false,
    rating: 4.6,
    downloads: 2900,
    workflows: ['Content → Analyze → Policy Check → Action → Log'],
    promptTemplate: 'Moderate this content: {{content}}. Policy: {{policy}}. Check for: toxicity, spam, PII, policy violations.',
    systemPrompt: 'You are a content moderator. Apply policies consistently and fairly. When uncertain, escalate to humans.',
    exampleConversation: ['User: Moderate this user comment', 'Agent: Flagged for toxic language (score: 0.92). Policy violated: Harassment. Action: Hidden. Escalated for review.'],
    deploymentStatus: 'ready',
    setupCommands: ['pip install nexify-moderation', 'nexify-moderation --configure'],
  },
]

// ── Helper Functions ──
export function getAgentById(id: string): AgentDefinition | undefined {
  return agentCatalog.find(a => a.id === id || a.slug === id)
}

export function getAgentsByCategory(category: AgentCategory): AgentDefinition[] {
  return agentCatalog.filter(a => a.category === category)
}

export function getAgentsByIndustry(industry: string): AgentDefinition[] {
  return agentCatalog.filter(a => a.industry.some(i => i.toLowerCase() === industry.toLowerCase()))
}

export function getFeaturedAgents(): AgentDefinition[] {
  return agentCatalog.filter(a => a.featured)
}

export function getTrendingAgents(): AgentDefinition[] {
  return agentCatalog.filter(a => a.trending)
}

export function searchAgents(query: string): AgentDefinition[] {
  const q = query.toLowerCase()
  return agentCatalog.filter(a =>
    a.name.toLowerCase().includes(q) ||
    a.description.toLowerCase().includes(q) ||
    a.category.toLowerCase().includes(q) ||
    a.industry.some(i => i.toLowerCase().includes(q))
  )
}

export const agentCategories: { category: AgentCategory; label: string; description: string; icon: string; count: number }[] = [
  { category: 'research', label: 'Research', description: 'Deep research, competitive analysis, and intelligence gathering', icon: '🔬', count: 0 },
  { category: 'coding', label: 'Coding', description: 'Code generation, review, testing, and database queries', icon: '💻', count: 0 },
  { category: 'data', label: 'Data', description: 'Analysis, visualization, document intelligence', icon: '📊', count: 0 },
  { category: 'content', label: 'Content', description: 'Writing, documentation, summaries, and notes', icon: '✍️', count: 0 },
  { category: 'communication', label: 'Communication', description: 'Email, social media, messaging', icon: '💬', count: 0 },
  { category: 'finance', label: 'Finance', description: 'Financial analysis, stock research, accounting', icon: '💰', count: 0 },
  { category: 'healthcare', label: 'Healthcare', description: 'Medical analysis, patient support, clinical data', icon: '🏥', count: 0 },
  { category: 'legal', label: 'Legal', description: 'Contract review, compliance, legal research', icon: '⚖️', count: 0 },
  { category: 'marketing', label: 'Marketing', description: 'Campaign creation, SEO, content strategy', icon: '📈', count: 0 },
  { category: 'sales', label: 'Sales', description: 'Lead generation, qualification, outreach', icon: '🤝', count: 0 },
  { category: 'support', label: 'Support', description: 'Customer service, issue triage, help desk', icon: '🎧', count: 0 },
  { category: 'devops', label: 'DevOps', description: 'Infrastructure, monitoring, CI/CD', icon: '🔧', count: 0 },
  { category: 'security', label: 'Security', description: 'Audit, vulnerability management, moderation', icon: '🛡️', count: 0 },
  { category: 'hr', label: 'HR', description: 'Recruitment, screening, career development', icon: '👥', count: 0 },
  { category: 'productivity', label: 'Productivity', description: 'Personal assistants, planning, organization', icon: '⚡', count: 0 },
  { category: 'education', label: 'Education', description: 'Tutoring, course creation, learning', icon: '📚', count: 0 },
  { category: 'ecommerce', label: 'E-commerce', description: 'Product management, recommendations, inventory', icon: '🛒', count: 0 },
  { category: 'social', label: 'Social', description: 'Social media management, community engagement', icon: '📱', count: 0 },
  { category: 'travel', label: 'Travel', description: 'Trip planning, recommendations, bookings', icon: '✈️', count: 0 },
  { category: 'analytics', label: 'Analytics', description: 'Business intelligence, metrics, reporting', icon: '📐', count: 0 },
]

// Populate counts
agentCategories.forEach(c => {
  c.count = getAgentsByCategory(c.category).length
})
